// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBf_Lnwwj5ckKzKC7Y08goyVq4eiumGI',
    appId: '1:660640360227:web:35f97de599d4f9ab508e96',
    messagingSenderId: '660640360227',
    projectId: 'unify-4ce06',
    authDomain: 'unify-4ce06.firebaseapp.com',
    storageBucket: 'unify-4ce06.firebasestorage.app',
    measurementId: 'G-B4T3N0MNS0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAIvBb-UUMqesRbATDHnlY35cbtHvh3cE',
    appId: '1:660640360227:ios:20fafcfa52c720f3508e96',
    messagingSenderId: '660640360227',
    projectId: 'unify-4ce06',
    storageBucket: 'unify-4ce06.firebasestorage.app',
    iosBundleId: 'com.example.unify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANBf_Lnwwj5ckKzKC7Y08goyVq4eiumGI',
    appId: '1:660640360227:web:14579fe3576dfcdc508e96',
    messagingSenderId: '660640360227',
    projectId: 'unify-4ce06',
    authDomain: 'unify-4ce06.firebaseapp.com',
    storageBucket: 'unify-4ce06.firebasestorage.app',
    measurementId: 'G-W208HGFDP2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAIvBb-UUMqesRbATDHnlY35cbtHvh3cE',
    appId: '1:660640360227:ios:20fafcfa52c720f3508e96',
    messagingSenderId: '660640360227',
    projectId: 'unify-4ce06',
    storageBucket: 'unify-4ce06.firebasestorage.app',
    iosBundleId: 'com.example.unify',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfYlozQKx35kV4EaF9PdCrBTNqJ_G0CY',
    appId: '1:660640360227:android:fd3afe95af62166e508e96',
    messagingSenderId: '660640360227',
    projectId: 'unify-4ce06',
    storageBucket: 'unify-4ce06.firebasestorage.app',
  );
}
